import React from 'react';
import {AbsoluteFill, Composition, Easing, Img, interpolate, registerRoot, staticFile, useCurrentFrame} from 'remotion';
import '@fontsource-variable/inter';

type Props={kind:string; title:string; labels:string[]; values:number[]; note:string; source:string; seconds:number; image?:string};
const ink='#202A29', paper='#EEEDE6', moss='#668176', slate='#667986';
const ease=Easing.bezier(.2,.7,.25,1);
const progress=(f:number,start=0,n=22)=>interpolate(f,[start,start+n],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
const Reveal:React.FC<{at?:number;children:React.ReactNode;style?:React.CSSProperties}>=({at=0,children,style})=>{const p=progress(useCurrentFrame(),at);return <div style={{opacity:p,transform:`translateY(${(1-p)*16}px)`,...style}}>{children}</div>};
const Brand=()=> <Img src={staticFile('brands/openai.svg')} style={{width:64,height:65,objectFit:'contain'}}/>;
const Credit:React.FC<{text:string}>=({text})=><div style={{position:'absolute',left:108,bottom:49,display:'flex',alignItems:'center',gap:16,color:'#596460',fontSize:23}}><span style={{width:28,height:2,background:'#596460'}}/>{text}</div>;
const DocumentIcon=({x,y,check=false}:{x:number;y:number;check?:boolean})=><g transform={`translate(${x} ${y})`}><path d="M0 0 H100 L136 36 V170 H0Z" fill={paper} stroke={ink} strokeWidth="4"/><path d="M100 0V36H136M22 69H110M22 93H92M22 117H104" fill="none" stroke={ink} strokeWidth="3"/>{check&&<path d="M72 146l16 14 33-39" fill="none" stroke={moss} strokeWidth="8"/>}</g>;
const Graphic:React.FC<Props>=(p)=>{
 const f=useCurrentFrame();
 return <AbsoluteFill style={{background:paper,color:ink,fontFamily:'Inter Variable, Arial',padding:108}}>
  <div style={{display:'flex',alignItems:'center',gap:26}}><Brand/><div style={{fontSize:30,fontWeight:550}}>GPT-6 Astra</div></div>
  <div style={{fontSize:68,lineHeight:1.1,fontWeight:650,letterSpacing:-2,marginTop:52,maxWidth:1580}}>{p.title}</div>
  {p.kind==='bars'&&<div style={{marginTop:70,marginLeft:30,width:1480}}>{p.labels.map((label,i)=><div key={label} style={{marginBottom:49}}><Reveal at={i*21}><div style={{fontSize:33,marginBottom:16}}>{label}</div></Reveal><div style={{display:'flex',alignItems:'center',gap:24}}><div style={{height:68,width:1160*(p.values[i]/100)*progress(f,12+i*21,36),background:i===0?moss:slate}}/><span style={{fontSize:55,fontWeight:600,opacity:progress(f,42+i*21)}}>{p.values[i]}%</span></div></div>)}<div style={{width:1160,borderTop:'2px solid #A3ADA5',display:'flex',justifyContent:'space-between',fontSize:23,paddingTop:9}}><span>0</span><span>25</span><span>50</span><span>75</span><span>100%</span></div></div>}
  {p.kind==='latency'&&<svg width="1650" height="460" style={{marginTop:50}}>{p.values.map((v,i)=><g key={i} transform={`translate(10 ${40+i*185})`}><text x="0" y="0" fill={ink} fontSize="32">{p.labels[i]}</text><line x1="0" y1="58" x2={1200*(v/75)*progress(f,10+i*28,42)} y2="58" stroke={i===0?moss:slate} strokeWidth="15"/><circle cx={1200*(v/75)*progress(f,10+i*28,42)} cy="58" r="13" fill={ink}/><text x="1260" y="77" fill={ink} fontSize="66">~{v} min</text></g>)}</svg>}
  {p.kind==='scope'&&<div style={{display:'flex',gap:95,marginTop:78,alignItems:'baseline'}}><Reveal at={8} style={{flex:1}}><div style={{fontSize:170,letterSpacing:-8,color:moss}}>~40<span style={{fontSize:90}}>%</span></div><div style={{fontSize:35,maxWidth:640,lineHeight:1.3}}>Financial-statement workflow</div></Reveal><Reveal at={55} style={{flex:1,borderLeft:'2px solid #A3ADA5',paddingLeft:85}}><div style={{fontSize:115,letterSpacing:-5}}>~3<span style={{fontSize:66}}>%</span></div><div style={{fontSize:35,lineHeight:1.3}}>All tasks in Legora’s<br/>broader benchmark</div></Reveal></div>}
  {p.kind==='documents'&&<svg width="1670" height="480" style={{marginTop:44}}>{Array.from({length:7},(_,i)=><g key={i} opacity={progress(f,8+i*4)}><DocumentIcon x={40+i*28} y={60+i*9}/></g>)}<text x="470" y="200" fill={ink} fontSize="110">41</text><text x="473" y="249" fill={ink} fontSize="30">documents</text><path d="M710 188H1010l-25-20m25 20-25 20" fill="none" stroke={moss} strokeWidth="5" strokeDasharray="340" strokeDashoffset={340*(1-progress(f,40,28))}/><g opacity={progress(f,70)}><DocumentIcon x={1110} y={78} check/><text x="1310" y="205" fill={ink} fontSize="72">4 / 4</text><text x="1308" y="250" fill={ink} fontSize="27">planted errors found</text></g></svg>}
  {p.kind==='branches'&&<svg width="1670" height="500" style={{marginTop:30}}><g opacity={progress(f)}><path d="M50 190l100-55 100 55-100 55zM50 190v110l100 55V245M250 190v110l-100 55" fill="none" stroke={ink} strokeWidth="5"/><text x="5" y="410" fontSize="33" fill={ink}>One playable foundation</text></g>{[0,1,2].map(i=><g key={i} opacity={progress(f,30+i*22)}><path d={`M340 245H570V${90+i*145}H720`} fill="none" stroke={slate} strokeWidth="3"/><rect x="748" y={38+i*145} width="88" height="96" fill={[moss,slate,'#92796C'][i]}/><text x="884" y={102+i*145} fill={ink} fontSize="40">Themed prototype {i+1}</text></g>)}</svg>}
  {p.kind==='price'&&<div style={{display:'flex',gap:120,marginTop:85}}>{p.labels.map((l,i)=><Reveal at={i*45} key={l} style={{flex:1,borderTop:`5px solid ${i?slate:moss}`,paddingTop:32}}><div style={{fontSize:35}}>{l}</div><div style={{fontSize:166,letterSpacing:-8,marginTop:8}}>${p.values[i]}</div><div style={{fontSize:31}}>per million tokens</div></Reveal>)}</div>}
  {(p.kind==='test'||p.kind==='flow'||p.kind==='boundaries')&&<div style={{marginTop:78}}>{p.labels.map((l,i)=><Reveal key={l} at={12+i*38} style={{display:'flex',alignItems:'center',gap:35,marginBottom:35}}><span style={{fontSize:40,color:slate,fontVariantNumeric:'tabular-nums'}}>0{i+1}</span><div style={{width:48,height:3,background:moss}}/><span style={{fontSize:51,fontWeight:500}}>{l}</span></Reveal>)}</div>}
  {p.kind==='image'&&<div style={{display:'flex',marginTop:50,gap:70,alignItems:'center'}}><Img src={staticFile(p.image!)} style={{width:980,height:500,objectFit:'cover'}}/><div>{p.labels.map((l,i)=><Reveal at={i*35} key={l}><div style={{fontSize:44,lineHeight:1.25,marginBottom:34,maxWidth:520}}>{l}</div></Reveal>)}</div></div>}
  <div style={{position:'absolute',left:112,bottom:122,fontSize:29,maxWidth:1590,lineHeight:1.35,color:'#465950'}}>{p.note}</div><Credit text={p.source}/>
 </AbsoluteFill>
};
const Thumbnail:React.FC<Props>=(p)=>{
 const header=<div style={{display:'flex',alignItems:'center',gap:30}}><Img src={staticFile('brands/openai.svg')} style={{width:145,height:147}}/><div style={{fontSize:50,fontWeight:650}}>GPT-6 Astra</div></div>;
 return <AbsoluteFill style={{background:paper,color:ink,fontFamily:'Inter Variable, Arial'}}>
 {p.kind==='thumb-result'?<><Img src={staticFile('astra/house.jpg')} style={{position:'absolute',left:755,top:0,width:1165,height:1080,objectFit:'cover'}}/><div style={{position:'absolute',left:0,top:0,width:800,height:1080,background:paper,padding:'74px 62px'}}>{header}<div style={{fontSize:123,fontWeight:760,lineHeight:1.02,letterSpacing:-5,marginTop:105}}>Beyond<br/>the <span style={{background:'#B8C6B6'}}>chat.</span></div><div style={{fontSize:32,marginTop:64}}>The official demos, explained.</div></div></>:
 p.kind==='thumb-gears'?<><div style={{position:'absolute',left:90,top:75}}>{header}</div><Img src={staticFile('astra/gears.jpg')} style={{position:'absolute',right:10,bottom:70,width:1350,height:760,objectFit:'contain'}}/><div style={{position:'absolute',left:90,top:360,fontSize:126,lineHeight:1,fontWeight:760,letterSpacing:-5}}>From words<br/>to <span style={{background:'#B8C6B6'}}>work.</span></div></>:
 p.kind==='thumb-price'?<><div style={{position:'absolute',left:90,top:70}}>{header}</div><div style={{position:'absolute',left:90,top:330,fontSize:124,fontWeight:760,lineHeight:1.07,letterSpacing:-5}}>What’s the<br/><span style={{background:'#B8C6B6'}}>real cost?</span></div><div style={{position:'absolute',right:115,top:265,borderLeft:'4px solid #7B8C82',paddingLeft:100}}><div style={{fontSize:164,fontWeight:650}}>$10</div><div style={{fontSize:34}}>input / million tokens</div><div style={{fontSize:164,fontWeight:650,marginTop:30}}>$50</div><div style={{fontSize:34}}>output / million tokens</div></div></>:
 <><Img src={staticFile('astra/unity.jpg')} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover'}}/><div style={{position:'absolute',left:65,top:55,background:paper,padding:'35px 45px'}}>{header}</div><div style={{position:'absolute',left:80,bottom:95,fontSize:115,fontWeight:770,background:paper,padding:'24px 35px',letterSpacing:-4}}>Check the <span style={{color:'#456652'}}>result.</span></div></>}
 </AbsoluteFill>
};
const defaults:Props={kind:'bars',title:'What did the desktop test measure?',labels:['GPT-6 Astra','GPT-5.6 Sol'],values:[72.6,65.7],note:'Reported offline evaluation. Not a success probability for your task.',source:'OpenAI · GPT-6 Astra launch',seconds:10};
registerRoot(()=><><Composition id="AstraGraphic" component={Graphic} width={1920} height={1080} fps={30} durationInFrames={300} defaultProps={defaults} calculateMetadata={({props})=>({durationInFrames:Math.round(props.seconds*30)})}/><Composition id="AstraThumbnail" component={Thumbnail} width={1920} height={1080} fps={30} durationInFrames={300} defaultProps={defaults}/></>);
